# this declares the new tenant
tenantProperties:
  tenants:
    OT:
      id: OT
      key: OT
      name: Other (sample tenant)

# every tenant will need to override archive settings
archive:
  tenants:
    OT:
      path-prefix: "OT"

# every tenant will need to override datasources
datasources:
  migrate_rw:
    tenants:
      OT:
        urlParts:
          database: migrate_olap_ot
        username:
        password:
  olap_ro:
    tenants:
      OT:
        username:
        password:
  olap_rw:
    tenants:
      OT:
        username:
        password:
  reporting_ro:
    tenants:
      OT:
        urlParts:
          database: reporting_ot
        username:
        password:
  reporting_rw:
    tenants:
      OT:
        urlParts:
          database: reporting_ot
        username:
        password:
  warehouse_rw:
    tenants:
      OT:
        urlParts:
          database: warehouse_ot
        username:
        password:

# This is an example of how to override default settings.
# Usually the state code/name will be set here.
# Tenant-specific localization is common too.
# The student fields setting is provided as an additional example.
reporting:
  tenants:
    OT:
      state:
        code: OT
        name: Other
      studentFields:
        Section504: disabled
#      translation-location: "binary-${spring.cloud.config.uri}/*/*/master/tenant-OT/"
