apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exam-processor-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: exam-processor
    spec:
      containers:
      - name: exam-processor
        image: smarterbalanced/rdw-ingest-exam-processor:1.2.0-RELEASE
        readinessProbe:
          httpGet:
            path: /health.json
            port: 8008
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 200m
            memory: 400M
          limits:
            cpu: 300m
            memory: 500M
        env:
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        ports:
        - containerPort: 8008
