apiVersion: v1
kind: PersistentVolume
metadata:
  name: iris-efs-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-[aws-randomization]
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iris-efs-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
