apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: migrate-olap-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: migrate-olap
    spec:
      containers:
      - name: migrate-olap
        image: smarterbalanced/rdw-ingest-migrate-olap:1.2.3-RELEASE
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 200m
            memory: 500M
          limits:
            cpu: 300m
            memory: 600M
        env:
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        ports:
        - containerPort: 8008
