apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: package-processor-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: package-processor
    spec:
      containers:
      - name: package-processor
        image: smarterbalanced/rdw-ingest-package-processor:1.4.0-RC17
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 200m
            memory: 500M
          limits:
            cpu: 300m
            memory: 600M
        env:
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        ports:
        - containerPort: 8008
