apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:[aws-randomization]"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 443
    targetPort: 8080
    name: https
  selector:
    app: reporting-server
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-status-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8008
  selector:
    app: reporting-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reporting-deployment
spec:
  replicas: 4
  revisionHistoryLimit: 2
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: reporting-server
    spec:
      containers:
      - name: webapp
        image: smarterbalanced/rdw-reporting-webapp:1.0.4-RELEASE
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 1G
          limits:
            cpu: 750m
            memory: 1180M
        env:
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        ports:
        - containerPort: 8080
        - containerPort: 8008
        volumeMounts:
        - mountPath: /itembank
          name: itembank
      volumes:
      - name: itembank
        persistentVolumeClaim:
          claimName: iris-efs-volume