apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8008
  selector:
    app: task-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: task-server-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: task-server
    spec:
      containers:
      - name: task-server
        image: smarterbalanced/rdw-ingest-task-service:1.0.1-RELEASE
        readinessProbe:
          httpGet:
            path: /health.json
            port: 8008
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 200m
            memory: 400M
          limits:
            cpu: 300m
            memory: 500M
        env:
        - name: CONFIG_SERVICE_URL
          value: "http://configuration-service"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        ports:
        - containerPort: 8008