# Annotated configuration for settings common across all applications
#
# This file should be named application.yml when served by the configuration server.
#
# To make maintenance of the system easier, it is recommended that the common properties
# for datasources, archive, reporting, logging be put here. Those properties are annotated
# in the files for the individual services that use them. And a couple are here for example.

reporting:
  client: SBAC

  # The embargo feature applies its rules for only the current school year, so it must be configured.
  # Although there is a default value for this setting (2019), it should be explicitly configured.
  school-year: 2019

  # Used throughout the applications, the state code/name.
  state:
    code: CA
    name: California

  # By default the system does not allow users to see test results from institutions outside their
  # permissions. Setting this property true allows users to see all test results for students
  # regardless of where the test was administered, if they have PII for the student.
#  transfer-access-enabled: false

logging:
  level:
    # this outputs a couple INFO messages every 5 minutes, annoying
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: warn
