# Annotated configuration for RDW Reporting Service.

# IRiS item files
# root is the root location of the files [ s3://some-bucket/ | file:///itembank/items/ | classpath: ]
# directory is like Item-{0}/ or item-content/bank/items/Item-{0}/
artifacts:
  root:
  exam-item:
    directory:
#    file-name: item-{0}.xml
