# Annotated configuration for RDW Exam Processor
#
# The spring application name is rdw-ingest-exam-processor so this file should be named
# rdw-ingest-exam-processor.yml when served by the configuration server.
#
# Properties that have a reasonable default value are commented out.
# Other properties are not commented out and must be provided.

# The actuator end-point is on a different port with no security because it is expected to be
# exposed only in a private subnet. Use the default settings unless you really know what you
# are doing.
management:
#  security:
#    enabled: false
server:
#  port: 8008
#  tomcat:
#    max-connections: 2
#    max-threads: 2

# Datasource configuration.
# Use defaults for most of the settings except server, username and password.
# The url-server should be set to the host and port, e.g. localhost:3306 or
# my-cluster.cluster-cimuvo5urx1e.us-west-2.rds.amazonaws.com:3306.
# The password should be encrypted.
datasources:
  warehouse_rw:
#    url-parts:
#      protocol: "jdbc:mysql:"
#      hosts: "${datasources.warehouse_rw.url-server:localhost:3306}"
#      database: "${datasources.warehouse_rw.url-schema:warehouse}"
#      properties: "useSSL=${datasources.warehouse_rw.use-ssl:false}\
#                   &useLegacyDatetimeCode=${datasources.warehouse_rw.use-legacy-datetime-code:false}\
#                   &characterEncoding=${datasources.warehouse_rw.character-encoding:utf8}\
#                   &rewriteBatchedStatements=${datasources.warehouse_rw.rewrite-batched-statements:true}\
#                   &noAccessToProcedureBodies=${datasources.warehouse_rw.no-access-to-procedure-bodies:true}\
#                   &connectTimeout=${datasources.warehouse_rw.connect-timeout:10000}\
#                   &socketTimeout=${datasources.warehouse_rw.socket-timeout:40000}\
#                   "
#    url: "${datasources.warehouse_rw.url-parts.protocol}//${datasources.warehouse_rw.url-parts.hosts}/${datasources.warehouse_rw.url-parts.database}?${datasources.warehouse_rw.url-parts.properties}"
#    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${datasources.warehouse_rw.query-timeout:30})"
    url-server:
    username:
    password:
#    testWhileIdle: true
#    validationQuery: SELECT 1
#    validationQueryTimeout: 10000
#    driverClassName: com.mysql.jdbc.Driver
#    initialize: false
#    initialSize: 6
#    maxActive: 12
#    minIdle: ${datasources.warehouse_rw.initialSize}
#    maxIdle: ${datasources.warehouse_rw.maxActive}
#    maxWait: 10000
#    removeAbandoned: false
#    removeAbandonedTimeout: 60
#    logAbandoned: false

# Spring application configuration.
spring:
  # RabbitMQ configuration.
  # There are no default values. The host must be set based on the orchestration environment
  # e.g. rabbit-service, with appropriate username and password. The password should be encrypted.
  rabbitmq:
    host:
    username:
    password:

# DB retry policy
# Defaults are good.
#jdbc:
#  retry:
#    default:
#      max-attempts: 4
#      delay: 30
#      multiplier: 2

# Transformations are applied to exam payloads before they are parsed and
# loaded as TDSReports. They are intended as a last resort when the 3rd party
# submitting the results are providing bad or malformed data. It is better,
# of course, to have conforming input without needing transformation.
# Currently only transformations using XSLT 1.0 and 2.0 are supported.
# There are NO default settings for this: by default no transformations will
# loaded or applied.
#transformations:
#  exam: "binary-${spring.cloud.config.uri}/*/*/master/xslt/exam.xsl"

# SBAC assessment validation settings.
# The default settings should be good.
#validation:
#  scaleScore:
#    min: 1500
#    max: 3500
#  thetaScore:
#    min: -5
#    max: 5
#  itemScore:
#    min: -1
#    max: 20
#  Enforcing configurable data elements to be required.
#  The complete list can be found in ConfigurableDataElement.java in https://github.com/SmarterApp/RDW_Ingest
#  requiredDataElements:
#    - FirstName
#    - LastOrSurname
#    - Birthdate
#    - Sex
#    - EconomicDisadvantageStatus
#    - IDEAIndicator
#    - SessionId
#    - Completeness
#    - AdministrationCondition
