# Annotated configuration for RDW Exam Processor
#
# There are no required property overrides for the exam processor.

#validation:
#  Enforcing configurable data elements to be required.
#  The complete list can be found in ConfigurableDataElement.java in https://github.com/SmarterApp/RDW_Ingest
#  requiredDataElements:
#    - FirstName
#    - LastOrSurname
#    - Birthdate
#    - Sex
#    - EconomicDisadvantageStatus
#    - IDEAIndicator
#    - SessionId
#    - Completeness
#    - AdministrationCondition
