# Annotated configuration for RDW Import Service.

# OAuth2 configuration.
# The OAuth2 URL is used to fetch info for the token, so it must have a placeholder for the token.
# For example, https://host/auth/oauth2/tokeninfo?access_token={access_token}. There is no default
# value for the URL, it must be provided. The permission-service end-point should correspond to the
# RESTful interface, for example https://host/rest.
security:
  oauth2:
    token-info-url:
  permission-service:
    endpoint:
