# Annotated configuration for RDW Admin Service.

spring:
  # admin datasources must be configured with users with elevated privileges
  admin_warehouse_datasource:
#    url-parts:
#      #This is the generic format of the connection URL protocol//[hosts][/database][?properties]
#      protocol: "jdbc:mysql:"
#      hosts: "${spring.admin_warehouse_datasource.url-server:localhost:3306}"
#      properties: "useSSL=${spring.admin_warehouse_datasource.use-ssl:false}\
#                   &useLegacyDatetimeCode=${spring.admin_warehouse_datasource.use-legacy-datetime-code:false}\
#                   &characterEncoding=${spring.admin_warehouse_datasource.character-encoding:utf8}\
#                   &connectTimeout=${spring.admin_warehouse_datasource.connect-timeout:10000}\
#                   &socketTimeout=${spring.admin_warehouse_datasource.socket-timeout:100000}\
#                   "
#    #not connecting to a specific schema for admin requires scoping for each query
#    url: "${spring.admin_warehouse_datasource.url-parts.protocol}//${spring.admin_warehouse_datasource.url-parts.hosts}?${spring.admin_warehouse_datasource.url-parts.properties}"
#    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${spring.admin_warehouse_datasource.query-timeout:240})"
    url-server:
    username:
    password:
#    testWhileIdle: true
#    validationQuery: SELECT 1
#    validationQueryTimeout: 10000
#    driverClassName: com.mysql.jdbc.Driver
#    initialize: false
#    initialSize: 0
#    maxActive: 2
#    minIdle: ${spring.admin_warehouse_datasource.initialSize}
#    maxIdle: ${spring.admin_warehouse_datasource.maxActive}
#    removeAbandoned: false
#    removeAbandonedTimeout: 60
#    logAbandoned: false

  admin_reporting_datasource:
#    url-parts:
#      #This is the generic format of the connection URL protocol//[hosts][/database][?properties]
#      protocol: "jdbc:mysql:"
#      hosts: "${spring.admin_reporting_datasource.url-server:localhost:3306}"
#      properties: "useSSL=${spring.admin_reporting_datasource.use-ssl:false}\
#                   &useLegacyDatetimeCode=${spring.admin_reporting_datasource.use-legacy-datetime-code:false}\
#                   &characterEncoding=${spring.admin_reporting_datasource.character-encoding:utf8}\
#                   &connectTimeout=${spring.admin_reporting_datasource.connect-timeout:10000}\
#                   &socketTimeout=${spring.admin_reporting_datasource.socket-timeout:100000}\
#                   "
#    #not connecting to a specific schema for admin requires scoping for each query
#    url: "${spring.admin_reporting_datasource.url-parts.protocol}//${spring.admin_reporting_datasource.url-parts.hosts}?${spring.admin_reporting_datasource.url-parts.properties}"
#    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${spring.admin_reporting_datasource.query-timeout:240})"
    url-server:
    username:
    password:
#    testWhileIdle: true
#    validationQuery: SELECT 1
#    validationQueryTimeout: 10000
#    driverClassName: com.mysql.jdbc.Driver
#    initialize: false
#    initialSize: 0
#    maxActive: 2
#    minIdle: ${spring.admin_reporting_datasource.initialSize}
#    maxIdle: ${spring.admin_reporting_datasource.maxActive}
#    removeAbandoned: false
#    removeAbandonedTimeout: 60
#    logAbandoned: false

  admin_olap_datasource:
#    url-parts:
#      protocol: "jdbc:redshift:"
#      hosts: "${spring.admin_olap_datasource.url-server:localhost:5432}"
#      database: "${spring.admin_olap_datasource.url-db:dev}"
#      properties: "ApplicationName=rdw-reporting-aggregate-service\
#                   &loginTimeout=${spring.admin_olap_datasource.connect-timeout:10}\
#                   &socketTimeout=${spring.admin_olap_datasource.socket-timeout:0}\
#                   "
#    url: "${spring.admin_olap_datasource.url-parts.protocol}//${spring.admin_olap_datasource.url-parts.hosts}/${spring.admin_olap_datasource.url-parts.database}?${spring.admin_olap_datasource.url-parts.properties}"
    url-server:
    url-db:
    username:
    password:
#    testWhileIdle: true
#    validationQuery: SELECT 1
#    validationQueryTimeout: 30000
#    driverClassName: com.amazon.redshift.jdbc42.Driver
#    initialize: false
#    initialSize: 0
#    maxActive: 2
#    minIdle: ${spring.admin_olap_datasource.initialSize}
#    maxIdle: ${spring.admin_olap_datasource.maxActive}
#    removeAbandoned: false
#    removeAbandonedTimeout: 60
#    logAbandoned: false

# this is the list of available datasets for sandboxes
sandbox-properties:
  sandboxDatasets:
    - label: Demo Dataset
      id: demo-dataset
    - label: SBAC Dataset
      id: sbac-dataset

# Tenant configuration is saved in the git configuration repository.
# The remote repository URI must match the repository setting for the
# configuration service, specified in configuration-service.yml.
# Provide credentials that allow writing to that repository. These may be
# different than the read-only credentials for the configuration service.
tenant-configuration-persistence:
  local-repository-uri: file:///tmp/rdw_config_local
  remote-repository-uri:
  git-username:
  git-password:
  author:
  author-email:
