# Annotated configuration for RDW Migrate Reporting

# Batch configuration.
# The batch size is the number of import ids migrated in one chunk/iteration. The batch size can
# be adjusted for performance: it is a trade off between size and overall throughput. Because the
# database is the limiting factor, only so much tweaking will have an effect. As an example, in a
# particular staging environment adjusting the batch size from 1000 to 2000 increased the overall
# migrate rate by 33% (from 33/s to 44/s) at the cost of a much larger application image.
# A batch size of 2000 offers good performance with reasonable resource utilization (-Xmx512m).
# The batch delay is the time to wait (in milliseconds) before starting the next migrate iteration.
migrate:
#  batch:
#    size: 2000
#    delay: 60000
