# Annotated configuration for RDW Aggregate Service.

# Aggregate report configuration.
#aggregate-reporting:
#  assessment-types: ica,sum,iab
#  statewide-user-assessment-types: sum
#  state-aggregate-assessment-types: sum

# Application configuration
#app:
#  aggregate-reports:
#    api-enabled: false
#    custom-aggregate-report-repository:
#      organization-partition-size: 10
#    query-pool-size: 6

  # The repository cache should be cleared whenever new data is migrated. Typically this is daily so the default
  # is to clear the cache every day at 2:00 am (GMT). This setting should be coordinated to happen after the migration
  # cron setting in rdw-ingest-migrate-olap.yml.
#  cache:
#    repository:
#      refresh-cron: "0 0 2 * * *"
