# Annotated configuration for RDW Reporting Service.
#
# The spring application name is rdw-reporting-service so this file should
# be named rdw-reporting-service when served by the configuration server.
#
# Properties that have a reasonable default value are commented out.
# Other properties are not commented out and must be provided.

# The actuator end-point is on a different port with no security because it is
# expected to be exposed only in a private subnet.
management:
#  port: 8008
#  security:
#    enabled: false

# Application configuration
app:
  analytics:
    trackingId:

  datamart:
    datasource:
#      url: "\
#        jdbc:mysql://${app.datamart.datasource.url-server:localhost:3306}/${app.datamart.datasource.url-schema:reporting}\
#        ?useSSL=${app.datamart.datasource.use-ssl:false}\
#        &useLegacyDatetimeCode=${app.datamart.datasource.use-legacy-datetime-code:false}\
#        &characterEncoding=${app.datamart.datasource.character-encoding:utf8}\
#        &useCompression=${app.datamart.datasource.use-compression:true}\
#        "
      url-server:
      username:
      password:
#      testWhileIdle: true
#      validationQuery: SELECT 1
#      driverClassName: com.mysql.jdbc.Driver
#      initialize: false

#  external-links:
#    interpretive-guide: https://portal.smarterbalanced.org/library/en/reporting-system-interpretive-guide.pdf
#    user-guide: https://portal.smarterbalanced.org/library/en/reporting-system-user-guide.pdf

  # IRiS configuration.
  # The vendor id is provided by SmarterBalanced
  iris:
    vendorId:

  # Historical results may not have item level data. This setting controls UI options for items,
  # it should be set to the beginning of the first school year that has item level data.
#  min-item-data-year: 2016

  # Installed language configuration (optional).
  # These are lists of available languages, not including english (which is always available).
  # Details for these properties are covered in the language runbook.
#  report-languages:
#  ui-languages:

#  state:
#    code: CA
#    name: California

# IRiS item files
# root is the root location of the files [s3://some-bucket/ | classpath: | etc]
# directory is like item-content/bank/items/Item-{0}/
artifacts:
  root:
  exam-item:
    directory:
#    file-name: item-{0}.xml

# AWS credentials are necessary if reading IRiS item files from S3
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      auto: false
      static: us-west-2

# Server configuration.
# Use the defaults unless you really know what you're doing.
server:
#  tomcat:
#    max-connections: 0
#    max-threads: 4
#    accept-count: 10
#  compression:
#    enabled: true
#    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,text/csv
