# Annotated configuration for RDW Reporting Web App.

# Permission service configuration
# endpoint is probably the public URL, e.g. https://perm.smarterbalanced.org/rest
permissionservice:
  endpoint:

# Application behavior
reporting:
  # Used for google analytics.
  analytics-tracking-id:

  # The guide URLs are used to provide links on the landing and home pages.
#  interpretive-guide-url: https://portal.smarterbalanced.org/library/en/reporting-system-interpretive-guide.pdf
#  user-guide-url: https://portal.smarterbalanced.org/library/en/reporting-system-user-guide.pdf

  # IRiS configuration.
  # The vendor id is provided by SmarterBalanced
  iris-vendor-id:

  # When a user is logged into SSO but does not have proper permissions to access the reporting application
  # an Access Denied page is displayed.  The default is a basic page presented within the application.
  # To provide an external page/site use the "redirect:url" format.
  # For example, redirect:http://external-site.com/access-denied
#  access-denied-url: forward:/assets/public/access-denied.html

  # When a user is not logged in and accesses the root of the web application, they are presented with a landing page.
  # The default page provides a screen with a link to login by linking to "/home".  To provide an external page/site
  # use the "redirect:url" format.  For example, redirect:http://reporting-site.com
#  landing-page-url: forward:/landing.html

  # Historical results may not have item level data. This setting controls UI options for items,
  # it should be set to the beginning of the first school year that has item level data.
#  min-item-data-year: 2016

  # Installed language configuration (optional).
  # These are lists of available languages, not including english (which is always available).
  # Details for these properties are covered in the language runbook.
#  report-languages:
#  ui-languages:

  # The percentile feature displays percentiles derived from normative data so teachers can better
  # evaluate the performance of their students. Because this requires additional configuration data
  # that may not be available to a tenant, this feature is disabled by default.
#  percentile-display-enabled: false

# SAML/SSO configuration
# The setting of these properties is covered in more detail in the deployment guide.
# The keystore path will be a binary configuration, e.g. 'binary-${spring.cloud.config.uri}/*/*/master/rdw-reporting.jks'
# IDP metadata URL example: 'https://sso.smarterbalanced.org/auth/saml2/jsp/exportmetadata.jsp?realm=/sbac'.
# The passwords should be encrypted.
saml:
  key-store-file:
  key-store-password:
  private-key-entry-alias:
  private-key-entry-password:
  idp-metadata-url:
  sp-entity-id:
  # SAML settings when hosting behind a load balancer or reverse proxy
  # To use this, set enabled to true and set the hostname, e.g. reporting.smarterbalanced.org
  load-balance:
    enabled: false
#    scheme: https
    hostname:
#    context-path: /
#    port: 8080
#    include-server-port: false

# Spring application configuration
spring:
  # Session cache configuration.
  # The default is to not cache session data. To enable caching (using redis), set the
  # session.store-type to "redis" and set the redis values
  session:
    store-type:
  redis:
    host:
    port:

# Netflix zuul configuration.
# The URLs must be set to match the environment, e.g. http://admin-service, the other defaults should be fine.
zuul:
#  set-content-length: true
#  FormBodyWrapperFilter:
#    pre: disable
#  host:
#    socket-timeout-millis: 100000
  routes:
    iris:
#      path: /iris/**
      # The URL should be the internal (private) route, e.g. http://internal-[aws-randomization]/iris/
      url:
#      stripPrefix: true
    admin-service:
#      path: /api/admin-service/**
      url:
#      stripPrefix: true
    aggregate-service:
#      path: /api/aggregate-service/**
      url:
#      stripPrefix: true
    report-processor:
#      path: /api/report-processor/**
      url:
#      stripPrefix: true
    reporting-service:
#      path: /api/reporting-service/**
      url:
#      stripPrefix: true
