# Annotated configuration for RDW Migrate OLAP
#
# The spring application name is rdw-ingest-migrate-olap so this file should be
# named rdw-ingest-migrate-olap.yml when served by the configuration server.
#
# Properties that have a reasonable default value are commented out.
# Other properties are not commented out and must be provided.

# The actuator end-point is on a different port with no security because it is expected to be
# exposed only in a private subnet. Use the default settings unless you really know what you
# are doing.
management:
#  security:
#    enabled: false
server:
#  port: 8008
#  tomcat:
#    max-connections: 2
#    max-threads: 2

# Migrate uses S3 to stage data. Although the data is written to by Aurora and read by Redshift
# the service must have a configured archive service to manage the files. All values must be
# provided.
archive:
  root:
  cloud:
    aws:
      credentials:
        accessKey:
        secretKey:
      region:
        auto: false
        static: us-west-2

# Migrate configuration.
migrate:
  # Migrate uses S3 to stage data. The location is relative to the archive bucket.
  # The role must be provided and must grant Redshift permissions to S3.
  aws:
#    location: MigrateOlap
    redshift:
      role:

  # The batch size is the number of records migrated in one iteration. The aggregate data store is
  # very good at ingesting large data sets so this value can be large and defaults to 10,000,000.
  # Increasing it can improve migrate performance but values over 10,000,000 require a large Redshift
  # instance.
  # By default the migration is scheduled to run once a day at 1:00 am (GMT). If this is changed, it should
  # be coordinated to happen before the repository cache flush in rdw-reporting-aggregate-service.yml.
#  olap-batch:
#    size: 10000000
#    # every day at 1:00 am
#    run-cron: "0 0 1 * * *"

# The embargo feature applies its rules for only the current school year, so it must be configured.
# Although there is a default value for this setting (2019), it should be explicitly configured.
# Normally this will be a shared setting in application.yml.
reporting:
  school-year:

# Datasource configuration. There are two datasources for migrate.
# Use defaults for most of the settings except server, username and password.
# The url-server should be set to the host and port, e.g. localhost:3306 or
# my-cluster.cluster-cimuvo5urx1e.us-west-2.rds.amazonaws.com:3306.
# The password should be encrypted.
datasources:
  migrate_rw:
#    url-parts:
#      protocol: "jdbc:mysql:"
#      hosts: "${datasources.migrate_rw.url-server:localhost:3306}"
#      database: "${datasources.migrate_rw.url-schema:migrate_olap}"
#      properties: "useSSL=${datasources.migrate_rw.use-ssl:false}\
#                   &useLegacyDatetimeCode=${datasources.migrate_rw.use-legacy-datetime-code:false}\
#                   &characterEncoding=${datasources.migrate_rw.character-encoding:utf8}\
#                   &connectTimeout=${datasources.migrate_rw.connect-timeout:10000}\
#                   &socketTimeout=${datasources.migrate_rw.socket-timeout:0}\
#                   "
#    url: "${datasources.migrate_rw.url-parts.protocol}//${datasources.migrate_rw.url-parts.hosts}/${datasources.migrate_rw.url-parts.database}?${datasources.migrate_rw.url-parts.properties}"
    url-server:
    username:
    password:
#    testWhileIdle: true
#    validationQuery: SELECT 1
#    validationQueryTimeout: 10000
#    driverClassName: com.mysql.jdbc.Driver
#    initialize: false
#    initialSize: 4
#    maxActive: 10
#    minIdle: ${datasources.migrate_rw.initialSize}
#    maxIdle: ${datasources.migrate_rw.maxActive}
#    removeAbandoned: false
#    removeAbandonedTimeout: 60
#    logAbandoned: false

  olap_rw:
#    url-parts:
#      protocol: "jdbc:redshift:"
#      hosts: "${datasources.olap_rw.url-server:localhost:5432}"
#      database: "${datasources.olap_rw.url-db:dev}"
#      properties: "ApplicationName=rdw-ingest-migrate-olap\
#                   &loginTimeout=${datasources.olap_rw.connect-timeout:10}\
#                   &socketTimeout=${datasources.olap_rw.socket-timeout:0}\
#                   "
#    url: "${datasources.olap_rw.url-parts.protocol}//${datasources.olap_rw.url-parts.hosts}/${datasources.olap_rw.url-parts.database}?${datasources.olap_rw.url-parts.properties}"
    url-server:
#    url-db: dev
    username:
    password:
#    testWhileIdle: true
#    validationQuery: SELECT 1
#    validationQueryTimeout: 30000
#    driverClassName: com.amazon.redshift.jdbc42.Driver

  warehouse_rw:
#    url-parts:
#      protocol: "jdbc:mysql:"
#      hosts: "${datasources.warehouse_rw.url-server:localhost:3306}"
#      database: "${datasources.warehouse_rw.url-schema:warehouse}"
#      properties: "useSSL=${datasources.warehouse_rw.use-ssl:false}\
#                   &useLegacyDatetimeCode=${datasources.warehouse_rw.use-legacy-datetime-code:false}\
#                   &characterEncoding=${datasources.warehouse_rw.character-encoding:utf8}\
#                   &connectTimeout=${datasources.warehouse_rw.connect-timeout:10000}\
#                   &socketTimeout=${datasources.warehouse_rw.socket-timeout:0}\
#                   "
#    url: "${datasources.warehouse_rw.url-parts.protocol}//${datasources.warehouse_rw.url-parts.hosts}/${datasources.warehouse_rw.url-parts.database}?${datasources.warehouse_rw.url-parts.properties}"
    url-server:
    username:
    password:
#    testWhileIdle: true
#    validationQuery: SELECT 1
#    validationQueryTimeout: 10000
#    driverClassName: com.mysql.jdbc.Driver
#    initialize: false
#    initialSize: 4
#    maxActive: 10
#    minIdle: ${datasources.warehouse_rw.initialSize}
#    maxIdle: ${datasources.warehouse_rw.maxActive}
#    maxWait: 10000
#    removeAbandoned: false
#    removeAbandonedTimeout: 60
#    logAbandoned: false
