# Annotated configuration for RDW Report Processor.

# Application configuration
app:
  # PDF Generator configuration.
  # URL should be the internal (private) route which is typically resolved by the orchestration
  # framework's DNS and should include port as necessary, e.g. http://wkhtmltopdf-service:8082.
  wkhtmltopdf:
    url:
